### PR TITLE
fix(core): only run core affinity for runtime workers; idempotent set…

### LINKED ISSUE #658: [Bug]: Core affinity setter being misused
### What happened?

Found in docker logs:

```
2025-10-09T15:09:34.357071Z  WARN helix_db::helix_gateway::gateway: CoreSetter::set_current called more times than cores.len() * threads_per_core. Core affinity not set
```

Potentially an off by one error

### Steps to reproduce

Start a local helix instance, view docker logs. Was using an instance in release mode but unsure if same in debug mode.

### Version

2.0.5

### Environment

Development/Local

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pantShrey**
…_current_once()

## Description
Fix: prevent CoreSetter::set_current() from running on blocking-pool threads
Why:
`on_thread_start` is invoked on thread creation (including Tokio’s blocking pool threads), which caused CPU affinity to be incorrectly applied to non-worker threads.
Switching to `on_thread_unpark` ensures the affinity is set only when a runtime worker thread is about to execute tasks, and introducing `set_current_once() `guarantees it runs only once per OS thread (guarded by thread-local state).

Changes:

Replace `on_thread_start(...set_current()) `with `on_thread_unpark(...set_current_once())` in `helix_gateway/gateway.rs`

Add `CoreSetter::set_current_once()` using a per-thread `OnceLock (TLS)` and `catch_unwind` safety guard
## Related Issues
Closes #658

## Checklist when merging to main

- [ ] No compiler warnings (if applicable)
- [ ] Code is formatted with `rustfmt`
- [ ] No useless or dead code (if applicable)
- [ ] Code is easy to understand
- [ ] Doc comments are used for all functions, enums, structs, and fields (where appropriate)
- [ ] All tests pass
- [ ] Performance has not regressed (assuming change was not to fix a bug)
- [ ] Version number has been updated in `helix-cli/Cargo.toml` and `helixdb/Cargo.toml`

## Additional Notes

<h2>Greptile Overview</h2>

Updated On: 2025-10-13 13:48:40 UTC

<h3>Summary</h3>

Fixed CPU core affinity being incorrectly applied to Tokio's blocking pool threads by switching from `on_thread_start` to `on_thread_unpark` and ensuring affinity is set only once per runtime worker thread.

**Key Changes:**
- Switched from `on_thread_start` to `on_thread_unpark` in runtime builder - ensures affinity only applies to runtime workers, not blocking pool threads
- Added `set_current_once()` method using thread-local `OnceLock` to guarantee idempotent behavior per OS thread
- Removed `catch_unwind` panic handling from `set_current_once()` (second commit)

**Analysis:**
The fix correctly addresses the warning by ensuring `CoreSetter::set_current()` is only called once per runtime worker thread. The `on_thread_unpark` hook runs when a worker is about to execute tasks, avoiding blocking pool threads entirely. The thread-local `OnceLock` guarantees idempotency across multiple unpark events on the same thread.

<details><summary><h3>Important Files Changed</h3></summary>

File Analysis

| Filename | Score | Overview |
|----------|-------|----------|
| helix-db/src/helix_gateway/gateway.rs | 4/5 | Changed from `on_thread_start` to `on_thread_unpark` and added `set_current_once()` to ensure core affinity is only set for runtime worker threads once per thread |

</details>

</details>

<details><summary><h3>Sequence Diagram</h3></summary>

```mermaid
sequenceDiagram
    participant Main as Main Thread
    participant TokioRT as Tokio Runtime Builder
    participant WorkerThread as Runtime Worker Thread
    participant CoreSetter as CoreSetter
    participant TLS as Thread-Local Storage

    Main->>CoreSetter: new(cores, threads_per_core=1)
    Main->>TokioRT: new_multi_thread()
    Main->>TokioRT: on_thread_unpark(closure)
    Main->>TokioRT: build()
    TokioRT->>WorkerThread: spawn worker threads
    
    Note over WorkerThread: Thread parked initially
    
    WorkerThread->>WorkerThread: Thread unparked for task
    WorkerThread->>CoreSetter: set_current_once()
    CoreSetter->>TLS: CORE_SET.with(|flag|)
    TLS->>CoreSetter: get_or_init(|| set_current())
    
    alt First unpark on this thread
        CoreSetter->>CoreSetter: set_current()
        CoreSetter->>CoreSetter: increment counter
        CoreSetter->>CoreSetter: calculate core_index
        CoreSetter->>WorkerThread: set_for_current(core_id)
        TLS->>TLS: Store () in OnceLock
    else Subsequent unparks
        TLS->>CoreSetter: Return existing ()
        Note over CoreSetter: No affinity change
    end
    
    WorkerThread->>WorkerThread: Execute task
    WorkerThread->>WorkerThread: Park again
```
</details>

### CODE REVIEW

File: helix-db/src/helix_gateway/gateway.rs [hunk 1]
```diff
@@ -240,4 +240,27 @@ impl CoreSetter {
...
+                }));
+
+                if res.is_err() {
+                    warn!(
+                        "CoreSetter::set_current_once panicked on thread {:?}",
+                        std::thread::current().id()
+                    );
+                }
+            });
+        });
```
Comment (matthewsanetra) [inline helix-db/src/helix_gateway/gateway.rs:253]: core_affinity doesn't panic and even if anything causes a panic here we'd want to crash on startup. There's also a clippy lint that the OnceLock::new(); should be in a `const { ... }`

```rust
    pub fn set_current_once(self: Arc<Self>) {
        use std::sync::OnceLock;

        thread_local! {
            static CORE_SET: OnceLock<()> = const { OnceLock::new() };
        }

        CORE_SET.with(|flag| {
            flag.get_or_init(move || self.set_current());
        });
    }
```

Comment (pantShrey) [reply helix-db/src/helix_gateway/gateway.rs:253]: Understood, will remove panic check. Sorry about missing the clippy check!

File: helix-db/src/helix_gateway/gateway.rs [hunk 2]
```diff
@@ -240,4 +240,17 @@ impl CoreSetter {
...
+    pub fn set_current_once(self: Arc<Self>) {
+        use std::sync::OnceLock;
+    
+        thread_local! {
+            static CORE_SET: OnceLock<()> = const { OnceLock::new() };
+        }
+    
+        CORE_SET.with(|flag| {
+            flag.get_or_init(move || self.set_current());
+        });
```
[the remark this answers is not in the document]
Comment (matthewsanetra) [reply helix-db/src/helix_gateway/gateway.rs:253]: Disregard this, the clone is explicit and done in the closure passed to on_thread_unpark, the performance difference is negligible and the move here isn't relevant to it.
