### PR TITLE
parser: feed render the contents of the file path

### LINKED ISSUE #681: [Bug]: Parsing problem
### What happened?

I was basically running the initial example provided by `helix init`, with a simple modification, and the error reporting is incorrect: 

```shell
[BUILD] Building instance 'dev'
[UPDATE] Updating Helix repository cache...
[SUCCESS] Helix repository updated
[PREPARE] Preparing workspace for 'dev'
[COPY] Copied cached repo to /home/mister/code/helix-thing/.helix/dev/helix-repo-copy
[COMPILE] Compiling Helix queries...
[CODEGEN] Generating Rust code from Helix queries...
[PARSE] Parsing Helix files...
[ANALYZE] Analyzing Helix files...
Compilation failed:

error[E204]: field `Label` is a reserved field name
   ┌─ /home/mister/code/helix-thing/./db/schema.hx:34:3
   │
34 │ // Example:
   │  ^^^^^^^^^^^^^
---> help: rename the field
```

### Steps to reproduce

1. start a helix project with helix init
2.  in schema.hx write something like: 
```hx
// Start building your schema here.
//
// The schema is used to to ensure a level of type safety in your queries.
//
// The schema is made up of Node types, denoted by N::,
// and Edge types, denoted by E::
//
// Under the Node types you can define fields that
// will be stored in the database.
//
// Under the Edge types you can define what type of node
// the edge will connect to and from, and also the
// properties that you want to store on the edge.
//
// Example:
//
// N::User {
//     Name: String,
//     Label: String,
//     Age: I64,
//     IsAdmin: Boolean,
// }
//
// E::Knows {
//     From: User,
//     To: User,
//     Properties: {
//         Since: I64,
//     }
// }

N::Mister {
	Name: String,
	Label: String,
	Age: I64,
	IsAdmin: Boolean
}
```

3. run `helix build dev`

### Version

2.0.5

### Environment

Development/Local

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by misterclayt0n**
## Description
this PR feeds `render()` with actual contents of `diagnostics.filepath` before rendering

## Related Issues
#681

Closes #681

## Checklist when merging to main

- [x] No compiler warnings (if applicable)
- [x] Code is formatted with `rustfmt`
- [x] No useless or dead code (if applicable)
- [x] Code is easy to understand
- [x] Doc comments are used for all functions, enums, structs, and fields (where appropriate)
- [x] All tests pass
- [x] Performance has not regressed (assuming change was not to fix a bug)
- [ ] Version number has been updated in `helix-cli/Cargo.toml` and `helixdb/Cargo.toml`

## Additional Notes
this is kind of an interesting problem, since @skemez reported he could not reproduce my issue, so, here's some screenshots:

before:
Screenshot_20251106_214123

after this PR:
Screenshot_20251106_213825

<h2>Greptile Overview</h2>

Updated On: 2025-11-07 00:45:26 UTC

<h3>Greptile Summary</h3>

This PR fixes a critical bug in HelixDB's error reporting system where diagnostic messages were displaying incorrect source code context. The issue was that the parser's error rendering function wasn't receiving the actual file contents when displaying compilation errors, causing it to show comment lines or completely wrong code snippets instead of the actual problematic code.

The fix introduces a `file_map` field to the `Content` struct that maps filenames to their actual content, and updates all compilation commands (`check`, `compile`, `build`, `push`) to pass this mapping to the `analyze_source` function. A new `diagnostic_source` utility function is added to properly resolve source text for error rendering with fallback mechanisms.

This change significantly improves the developer experience by ensuring that when HelixQL compilation fails, users see the correct code context rather than misleading information, making debugging much more effective.

<details><summary><h3>Important Files Changed</h3></summary>

| Filename | Score | Overview |
|----------|-------|-----------|
| helix-db/src/helixc/parser/types.rs | 5/5 | Adds `file_map` HashMap field to Content struct for filename-to-content mapping |
| helix-db/src/helixc/parser/mod.rs | 4/5 | Creates file_map during parsing by collecting filename-content pairs from files vector |
| helix-cli/src/utils.rs | 4/5 | Introduces `diagnostic_source` function with three-tier lookup strategy for proper source resolution |
| helix-cli/src/commands/check.rs | 5/5 | Passes file_map to analyze_source function to enable correct error rendering |
| helix-cli/src/commands/compile.rs | 4/5 | Updates analyze_source call to include file_map parameter for proper diagnostics |
| helix-cli/src/commands/build.rs | 4/5 | Adds file_map creation and updates diagnostic rendering to use correct source mapping |
| helix-cli/src/commands/push.rs | 5/5 | Constructs file_map in parse_queries_for_metrics to fix error context display |
</details>

**Context used:**

- Context from `dashboard` - readme for helixdb ([source](https://app.greptile.com/review/custom-context?memory=128beba4-b562-4fe4-b7ba-aef1f5b3f204))
- Context from `dashboard` - Main documentation for all of HelixDB, the SDKs, HelixQL, and the Helix CLI ([source](https://app.greptile.com/review/custom-context?memory=861865e1-0cf9-4602-a499-40c0c360142c))

### CODE REVIEW

**Comment by ishaksebsib** [comment]
Hi @misterclayt0n, I guess this is a similar issue to #429

File: helix-db/src/helixc/parser/types.rs [hunk 1]
```diff
@@ -15,6 +15,8 @@ pub struct Content {
     pub source: Source,
     /// Files in the content
     pub files: Vec<HxFile>,
+    /// Lookup map for file contents by path
+    pub file_map: HashMap<String, String>,
```
Comment (ishaksebsib) [inline helix-db/src/helixc/parser/types.rs]: I think we can avoid adding the new `file_map` field, since the `files` field already contains both the path and content, we can rely on that instead of maintaining a separate map

Comment (xav-db) [reply helix-db/src/helixc/parser/types.rs]: I agree with this

**Comment by misterclayt0n** [comment]
hm, #429 was merged 2 months ago. was I the only one to see the issue I've described tho?

File: helix-db/src/helixc/parser/types.rs (hunk 1 above)
Comment (misterclayt0n) [reply helix-db/src/helixc/parser/types.rs]: okay that makes sense

**Comment by ishaksebsib** [comment]
> hm, #429 was merged 2 months ago. was I the only one to see the issue I've described tho?

Yeah, I'm getting the same error too. PR #429 was overridden when CLI v2 was merged, so the fix doesn't exist now

**Comment by misterclayt0n** [comment]
I see, I'll refactor this code to remove `file_map` and better use the structure we already have then

**Comment by misterclayt0n** [comment]
done @ishaksebsib

**Review by xav-db — COMMENTED** [review]
This looks good I believe! @ishaksebsib Thoughts?

**Comment by ishaksebsib** [comment]
> This looks good I believe! @ishaksebsib Thoughts?

LGTM too

**Review by xav-db — APPROVED** [review]
LGTM
