### PR TITLE
fix overwriting gitignore in initializaiton

### LINKED ISSUE #876: [Bug]: helix init clears .gitignore
### What happened?

After running `helix init`, .gitignore is wiped and overwritten when really this should be an additive procedure

### Steps to reproduce

Run `helix init` in a folder with a non-empty `.gitignore`

### Version

2.3.0

### Environment

Self-hosted

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CodeMan62**
## Description
when we initialization helix with `helix init` in a folder that contains a .gitignore with some content that got wriped and overwritten. this PR fixes that 
## Related Issues
Closes #876 

## Checklist when merging to main

- [ ] No compiler warnings (if applicable)
- [ ] Code is formatted with `rustfmt`
- [ ] No useless or dead code (if applicable)
- [ ] Code is easy to understand
- [ ] Doc comments are used for all functions, enums, structs, and fields (where appropriate)
- [ ] All tests pass
- [ ] Performance has not regressed (assuming change was not to fix a bug)
- [ ] Version number has been updated in `helix-cli/Cargo.toml` and `helixdb/Cargo.toml`

## Additional Notes

<h3>Greptile Summary</h3>

Changed `.gitignore` handling from overwrite to append mode to preserve existing content when running `helix init`.

- Reads existing `.gitignore` content before adding new entries
- Only appends lines that don't already exist
- Fixes issue #876 where existing `.gitignore` was being wiped

**Issue found**: The duplicate check uses substring matching (`existing.contains(line)`) which can cause false positives - e.g., if `.gitignore` contains `my-target/`, the check for `target/` will incorrectly skip adding it.

<details><summary><h3>Important Files Changed</h3></summary>

| Filename | Overview |
|----------|----------|
| helix-cli/src/commands/init.rs | Fixed gitignore overwriting, but substring matching logic has edge case bugs |

</details>

</details>

<sub>Last reviewed commit: 3e51c60</sub>

### CODE REVIEW

File: helix-cli/src/commands/init.rs [hunk 1]
```diff
@@ -338,13 +339,22 @@ fn create_project_structure(
...
 "#;
     let gitignore_path = project_dir.join(".gitignore");
-    fs::write(&gitignore_path, gitignore)?;
+    let existing = fs::read_to_string(&gitignore_path).unwrap_or_default();
+    let mut file = fs::OpenOptions::new()
+        .create(true)
+        .append(true)
+        .open(&gitignore_path)?;
+    for line in gitignore.lines() {
+        if !existing.contains(line) {
```
[the remark this answers is not in the document]
Comment (xav-db) [reply helix-cli/src/commands/init.rs]: @CodeMan62 I think this comment is valid

File: helix-cli/src/commands/init.rs [hunk 2]
```diff
@@ -338,13 +339,22 @@ fn create_project_structure(
...
 
-    // Create .gitignore
+    // add this to .gitignore
     let gitignore = r#".helix/
 target/
 *.log
 "#;
     let gitignore_path = project_dir.join(".gitignore");
-    fs::write(&gitignore_path, gitignore)?;
+    let existing = fs::read_to_string(&gitignore_path).unwrap_or_default();
```
Comment (xav-db) [inline helix-cli/src/commands/init.rs:348]: I think greptile is accurate here! please update

Comment (CodeMan62) [reply helix-cli/src/commands/init.rs:348]: Done

**Comment by tika** [comment]
Thx!
